-- 현장별 메일함(/site-mails)의 현장 목록을 대외기관 점검(/sites)의 sites 테이블에서 분리한다(2026-10-01 사용자 요청:
-- "두 메뉴 사이에 현장관리에서 추가하는 현장은 연계가 되지 않게 해야 해. 현장 삭제하면 연동돼서 지워지고 있어").
-- 지금까지 site_mail_posts.site_id가 sites(id)를 on delete cascade로 참조해서, 메일함 화면에서 현장을 지우면
-- 대외기관 점검의 현장과 점검 기록까지 함께 삭제됐다. 이후로는 메일함 전용 site_mail_sites만 참조한다.
--
-- 쓰기 권한도 members.site_id(점검 현장 소속)가 아니라 메일함 현장별 "담당자"(site_mail_site_writers)로 판정한다.
-- 본사(admin/manager)는 여전히 모든 메일함 현장에 쓸 수 있다.
--
-- 시작 상태: 현재 sites의 현장들을 같은 id로 site_mail_sites에 복사해 기존 메일(site_mail_posts.site_id)이 그대로 유지되게 하고,
-- 지금 그 현장에 소속된 현장 계정(members.site_id)을 해당 메일함 현장의 담당자로 옮겨 기존 권한을 보존한다.
-- 복사 이후로는 두 목록이 완전히 독립적이다.

create table if not exists public.site_mail_sites (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_mail_site_writers (
  site_id bigint not null references public.site_mail_sites (id) on delete cascade,
  member_id text not null references public.members (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (site_id, member_id)
);

create index if not exists site_mail_site_writers_member_id_idx on public.site_mail_site_writers (member_id);

-- 기존 현장을 같은 id로 복사(이미 있으면 건너뜀) 후 identity 시퀀스를 최대 id 뒤로 맞춘다.
insert into public.site_mail_sites (id, name, sort_order)
overriding system value
select id, name, sort_order from public.sites
on conflict (id) do nothing;

-- 기존 메일 중 sites에서 이미 사라진 현장을 가리키는 행이 있다면(이론상 cascade로 없어야 함) 고아가 되지 않도록 정리한다.
delete from public.site_mail_posts p
where not exists (select 1 from public.site_mail_sites s where s.id = p.site_id);

select setval(
  pg_get_serial_sequence('public.site_mail_sites', 'id'),
  greatest((select coalesce(max(id), 0) from public.site_mail_sites), 1),
  (select count(*) > 0 from public.site_mail_sites)
);

insert into public.site_mail_site_writers (site_id, member_id)
select m.site_id, m.id
from public.members m
join public.site_mail_sites s on s.id = m.site_id
where m.site_id is not null and m.role not in ('admin', 'manager')
on conflict do nothing;

-- site_mail_posts의 참조 대상을 sites -> site_mail_sites로 교체한다.
alter table public.site_mail_posts drop constraint if exists site_mail_posts_site_id_fkey;
alter table public.site_mail_posts
  add constraint site_mail_posts_site_id_fkey foreign key (site_id) references public.site_mail_sites (id) on delete cascade;

alter table public.site_mail_sites enable row level security;
alter table public.site_mail_site_writers enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'site_mail_sites' and policyname = 'site_mail_sites_no_direct_access'
  ) then
    create policy "site_mail_sites_no_direct_access" on public.site_mail_sites
      for all to anon, authenticated using (false) with check (false);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'site_mail_site_writers' and policyname = 'site_mail_site_writers_no_direct_access'
  ) then
    create policy "site_mail_site_writers_no_direct_access" on public.site_mail_site_writers
      for all to anon, authenticated using (false) with check (false);
  end if;
end $$;
