-- 현장별 메일함(/site-mails)의 구분자(카테고리)를 부서별 업무기준(/task-standards)의 standard_categories에서 분리한다
-- (2026-10-02 사용자 요청: "(본사) 부서별 업무기준과 (현장) 현장별 메일함은 별개야. 구분자가 이렇게 바뀌어 버리면 안돼.
-- 현장은 본인 입맛에 맞게 바꿔서 쓰는 거야"). 지금까지 site_mail_posts.category_id가 standard_categories를 참조하고
-- 메일함 화면의 구분자 관리가 같은 테이블을 수정해서, 현장에서 바꾼 구분자가 본사 화면에도 그대로 반영됐다.
--
-- 시작 상태: 현재 standard_categories를 같은 id로 site_mail_categories에 복사해(현장에서 손본 현재 상태를 그대로 출발점으로)
-- 기존 메일의 category_id가 그대로 유지되게 한다. 복사 이후로는 두 목록이 완전히 독립적이다.
-- 복사가 끝난 뒤 본사 구분자(standard_categories)는 메일함에서 손대기 전 상태(레거시 standards.db에서 이관한 값)로 되돌린다.

create table if not exists public.site_mail_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  color text not null default '#6b7280',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  constraint site_mail_categories_name_key unique (name)
);

insert into public.site_mail_categories (id, name, color, sort_order)
overriding system value
select id, name, color, sort_order from public.standard_categories
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.site_mail_categories', 'id'),
  greatest((select coalesce(max(id), 0) from public.site_mail_categories), 1),
  (select count(*) > 0 from public.site_mail_categories)
);

-- site_mail_posts의 구분자 참조 대상을 standard_categories -> site_mail_categories로 교체한다.
alter table public.site_mail_posts drop constraint if exists site_mail_posts_category_id_fkey;
alter table public.site_mail_posts
  add constraint site_mail_posts_category_id_fkey foreign key (category_id) references public.site_mail_categories (id) on delete set null;

-- 본사 구분자 복원(2026-10-02 사용자 확인 화면 기준: 업무기준/시공기준/기 타). id 매핑은 scripts/migrate-task-standards.mjs 이관 순서와 같다.
-- 메일함에서 새로 추가된 구분자(본사 게시글이 쓰지 않는 id)는 본사 목록에서 제거한다 — 메일함 쪽에는 위에서 복사돼 남아 있다.
update public.standard_categories set name = name || '__restore_tmp' where id in (3, 4, 5);
update public.standard_categories set name = '업무기준', color = '#52bb25', sort_order = 0 where id = 3;
update public.standard_categories set name = '시공기준', color = '#ea580c', sort_order = 10 where id = 4;
update public.standard_categories set name = '기 타', color = '#6b7280', sort_order = 30 where id = 5;
delete from public.standard_categories c
where c.id not in (3, 4, 5)
  and not exists (select 1 from public.standard_posts p where p.category_id = c.id);

alter table public.site_mail_categories enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'site_mail_categories' and policyname = 'site_mail_categories_no_direct_access'
  ) then
    create policy "site_mail_categories_no_direct_access" on public.site_mail_categories
      for all to anon, authenticated using (false) with check (false);
  end if;
end $$;
